### ISSUE TITLE
trouble with elgg-system-messages after enabling mmenu

### ISSUE THREAD

**Issue by rheman** [ColdTrick/mmenu#2]
- Elgg v3.3.1
- mmenu v2.0
- composer install

Hi, first of all thank you for this incredible menu.

I have one bug.

When using the plugin I have some trouble with elgg-system-messages;
for instance when I like a post, the elgg-system-messages is displayed but I cannot see it on the top I need to scroll from down to top of the site to see the elgg-system-messages.

Did someone have the same behavior on their site?
Could someone help me with this issue ?

Regards,

**Comment by jdalsem** [comment]
i have currently no solution for this... fixed styled elements behave different in 'transformed' containers https://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/

If you have a custom theme, you might be able to change the behaviour of the system messages...

**Comment by jdalsem** [comment]
In Elgg 4.0 this is no longer an issue AFAICT
